### ISSUE TITLE
Muy buena aportación

### ISSUE THREAD

**Issue by jesusdra** [yousefkotp/VaCarTion#1]
Hola, 

simplemente, escribirte y decirte que muy buena aportación, estaba buscando algo parecido, he tenido que modificar un par de cosas y añadir algo (por ejemplo, posibilidad de quitar la reserva) y me va a servir mucho.

Un trabajo muy bueno, lo que habéis hecho y mis felicitaciones.

Si queréis que os pase la forma de borrar la reserva, os lo puedo pasar sin problema, también he quitado el coste, ya que es algo individual y no tendría coste el alquiler.

**Comment by yousefkotp** [comment]
Hi, 
Thank you so much for your appreciation, kindly retype your message in English since no one in the project's contributors know Spanish and the translation of the message is not clear. However, what I understood is that you have added a feature to the system.
Contributions are welcomed for this project, kindly submit a pull request and we will review it.

**Comment by jesusdra** [comment]
Hello, 

My English is very bad and I am going to use the deepl translator, it has been very useful as a basis to use it for an app that I have in mind to reserve cars in my house, we have several cars and know who uses each car. 

With respect to the pull request, I can not do it because I have removed your content for my application and this would remove you the same, I can send you if you want the code here for you to see it and adapt it if you want in your code, I would not mind anything the truth.

I have removed the payment issue in general, I have modified all the queries related to the payment. I have added the possibility to cancel the reservation if it is before the start date and then a new page to put the kilometers to start the reservation, the kilometers end to leave the car, observations (for example, no wipers, does not work intermittent, a light on the dashboard ...) 

I have also seen that you have installed the nodemailer plugin, but I have not seen that you are using it anywhere, is it so? or I have not been able to see that you are using it, if so, what do you use it for, it would be very helpful, as I also want to implement the issue of email alerts for ITV (a periodic inspection that pass cars in Spain to check the car in general lines, if not passed, is not suitable for driving the car and you can be reported), for warnings of oil changes based on the kilometers that are added later to the reserve ...., 

I hope you understand me better in this message, greetings.

Translated with www.DeepL.com/Translator (free version)

**Comment by yousefkotp** [comment]
I understood you very clearly, I am really glad with all the progress you made, you can chat with me on [discord](https://discord.com/users/696474163723894869). You can send me the cancel reservation feature you built there.

Concerning the nodemailer part, you can find the nodemailer being used inside the "index.js" file on the post request for the endpoint "/signup". The nodemailer is used to send email to welcome new users to our system, you can use it wherever you want just make sure you adjust the .env file as discussed [here](https://github.com/yousefkotp/VaCarTion#deployment)

![image](https://user-images.githubusercontent.com/41492875/230597824-aa618722-b87e-4b62-ac44-72c12b35ca8b.png)

Since the issue opened here is actually irrelevant to the project, I would like us to continue our chat on discord and I would be happy to answer any further questions.
